version: '3'

services:
  nuxt-web:
    image: hasura-allow-list-manager-nuxt
    ports:
      - "127.0.0.1:3011:3011"
  python-hasura:
    image: hasura-allow-list-manager-python
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "127.0.0.1:5151:5151"
    env_file:
      - env_hasura_python